"""se agregaron relaciones

Revision ID: 3a1f63374161
Revises: c0b7773b7f84
Create Date: 2024-11-02 19:24:39.891058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1f63374161'
down_revision = 'c0b7773b7f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categoria', ['categoria_idcategoria'], ['idcategoria'])

    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_idcliente', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'clientes', ['cliente_idcliente'], ['idcliente'])

    with op.batch_alter_table('ordenitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('componente_idcomponente', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'componentes', ['componente_idcomponente'], ['idcomponente'])

    with op.batch_alter_table('sesion_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_idcliente', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('carrito_idcarrito', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'carritos', ['carrito_idcarrito'], ['idcarrito'])
        batch_op.create_foreign_key(None, 'clientes', ['cliente_idcliente'], ['idcliente'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesion_usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carrito_idcarrito')
        batch_op.drop_column('cliente_idcliente')

    with op.batch_alter_table('ordenitems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('componente_idcomponente')

    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_idcliente')

    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
