"""carrito a cliente

Revision ID: 709453c74356
Revises: f8043331b2de
Create Date: 2024-10-24 00:40:30.930845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '709453c74356'
down_revision = 'f8043331b2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('clave', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Componentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Carritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', 'VACIO', name='estado'), nullable=True),
    sa.Column('cantidad_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Carrito_Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=True),
    sa.Column('componente_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('fecha_agregado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrito_id'], ['Carritos.id'], ),
    sa.ForeignKeyConstraint(['componente_id'], ['Componentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('carrito_items')
    op.drop_table('componentes')
    op.drop_table('carritos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('clave', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('ultima_actividad', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('carritos',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=True),
    sa.Column('estado', mysql.ENUM('ABIERTO', 'CERRADO', 'VACIO'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='carritos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('componentes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descripcion', mysql.TEXT(), nullable=True),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('categoria', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carrito_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('carrito_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('componente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fecha_agregado', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id'], name='carrito_items_ibfk_1'),
    sa.ForeignKeyConstraint(['componente_id'], ['componentes.id'], name='carrito_items_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Carrito_Items')
    op.drop_table('Carritos')
    op.drop_table('Componentes')
    op.drop_table('Clientes')
    # ### end Alembic commands ###
