"""se agregaron cosas

Revision ID: a4f3c3a616d3
Revises: f8043331b2de
Create Date: 2024-10-31 18:21:34.781760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f3c3a616d3'
down_revision = 'f8043331b2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_items', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.drop_column('cantidad_items')

    # ### end Alembic commands ###
