"""se agregaron nuevas tablas

Revision ID: c0b7773b7f84
Revises: a4f3c3a616d3
Create Date: 2024-11-01 23:04:03.098160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0b7773b7f84'
down_revision = 'a4f3c3a616d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direccion',
    sa.Column('iddireccion', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=45), nullable=False),
    sa.Column('ciudad', sa.String(length=45), nullable=False),
    sa.Column('provincia', sa.String(length=45), nullable=False),
    sa.Column('codigo_postal', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('iddireccion')
    )
    op.create_table('ordenitems',
    sa.Column('idordenitems', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_al_comprar', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idordenitems')
    )
    op.create_table('sesion_usuario',
    sa.Column('idsesion_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idsesion_usuario')
    )
    with op.batch_alter_table('carrito_items', schema=None) as batch_op:
        batch_op.drop_constraint('carrito_items_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('carrito_items_ibfk_2', type_='foreignkey')
        batch_op.drop_column('componente_id')
        batch_op.drop_column('fecha_agregado')
        batch_op.drop_column('carrito_id')

    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idcarrito', sa.Integer(), nullable=False))
        batch_op.drop_constraint('carritos_ibfk_1', type_='foreignkey')
        batch_op.drop_column('cliente_id')
        batch_op.drop_column('id')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('cantidad_items')
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idcliente', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')
        batch_op.drop_column('ultima_actividad')
        batch_op.drop_column('direccion')

    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idcomponente', sa.Integer(), nullable=False))
        batch_op.drop_column('id')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('componentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('idcomponente')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ultima_actividad', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('idcliente')

    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('cantidad_items', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('carritos_ibfk_1', 'clientes', ['cliente_id'], ['id'])
        batch_op.drop_column('idcarrito')

    with op.batch_alter_table('carrito_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrito_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_agregado', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('componente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('carrito_items_ibfk_2', 'componentes', ['componente_id'], ['id'])
        batch_op.create_foreign_key('carrito_items_ibfk_1', 'carritos', ['carrito_id'], ['id'])

    op.drop_table('sesion_usuario')
    op.drop_table('ordenitems')
    op.drop_table('direccion')
    # ### end Alembic commands ###
